### ISSUE TITLE
Curious about missing type of items, properties and scraping script

### ISSUE THREAD

**Issue by ckuijjer** [ashish01/hn-data-dumps#1]
First of all thanks for the work! I was looking for an up to date data dump of Hacker News and this seems like a really promising start!

Looking through the data dump and comparing it to the examples in the [Hacker News API readme](https://github.com/HackerNews/API#items) it seems that only _story_ and _ask_ are available, _comment_, _job, _poll_, and _part of poll_ don't seem to be part of the data dump.

Looking at the properties of the example story it seems that only a few properties are available, e.g. _descendants_, _kids_, _score_ etc are missing.

```
sqlite> SELECT * FROM hn_stories WHERE ID = 8863;
8863|{"by":"dhouston","time":1175714200,"title":"My YC app: Dropbox - Throw away your USB drive","url":"http://www.getdropbox.com/u/2/screencast.html"}
```

Example from https://hacker-news.firebaseio.com/v0/item/8863.json?print=pretty:

```
{
  "by" : "dhouston",
  "descendants" : 71,
  "id" : 8863,
  "kids" : [ 8952, 9224, 8917, 8884, 8887, 8943, 8869, 8958, 9005, 9671, 8940, 9067, 8908, 9055, 8865, 8881, 8872, 8873, 8955, 10403, 8903, 8928, 9125, 8998, 8901, 8902, 8907, 8894, 8878, 8870, 8980, 8934, 8876 ],
  "score" : 111,
  "time" : 1175714200,
  "title" : "My YC app: Dropbox - Throw away your USB drive",
  "type" : "story",
  "url" : "http://www.getdropbox.com/u/2/screencast.html"
}
```

I'm curious if you also scraped the other type of items, and the other properties of e.g. a story, and if it would be possible to also include those in the data dump or to share the script used for scraping.

**Comment by ashish01** [comment]
You are right, in the snapshot I only added items of type story and removed some json fields to reduce the overall size. I will update the readme to reflect this.

I have also added the download script I used to scrap all 25M+ items from Firebase but use it responsibly, specifically don't change the default number of concurrent connections (default is 100).
