### ISSUE TITLE
Resumable?

### ISSUE THREAD

**Issue by breck7** [ashish01/hn-data-dumps#2]
I followed your readme and it *seems* like it's working:

```
  0%|                                                                                                                                         | 11648/32557237 [00:19<16:36:06, 544.55it/s]
```

Problem is if the script gets interrupted (ie, close my laptop lid, or lose network), it seems to start over.

Would it be hard to make this resumable?

**Comment by ashish01** [comment]
The code is setup in a way that it should be resumable but the DB defaults were not very amenable to that. I have changed it in the latest commit. I tested it locally by killing the process after running for a minute and it seemed to work OK. Let me know what you find!

**Comment by chapmanjacobd** [comment]
You can run a query like this to check for any gaps in your id column

```sql
WITH t AS (
    SELECT id AS latest_id,
        LAG (id, 1) OVER (ORDER BY id) AS oldest_id,
        id - (LAG (id, 1) OVER (ORDER BY id)) AS diff
    FROM (
        SELECT id FROM hn_story
        {'UNION ALL SELECT id FROM hn_comment' if 'hn_comment' in tables else ''}
        {'UNION ALL SELECT id FROM hn_job' if 'hn_job' in tables else ''}
        {'UNION ALL SELECT id FROM hn_poll' if 'hn_poll' in tables else ''}
        {'UNION ALL SELECT id FROM hn_pollopt' if 'hn_pollopt' in tables else ''}
    )
)
SELECT * FROM t
WHERE diff > 1
ORDER BY diff DESC
```

edit: https://github.com/ashish01/hn-data-dumps/issues/1 ahh sounds like there are going to be missing ids. I guess this SQL is not so helpful

**Comment by ashish01** [comment]
I have moved from Sqlite to storing data as parquet and also made resuming a bit more visible.

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/151985/213846073-74e73790-bb5a-4125-9262-3f13db67de5a.png">
